#ifndef __485_ADDRESS__h
#define __485_ADDRESS__h

enum address_485 {
// RW参数
    // 小车参数
    car_mode = 0,
    car_default_mode,
    light_control,
    error_get_and_clear,
    wheel_distance,
    axles_distance,
    software_reset,
    can_reinitialize,
    para_save,
    para_save_num,
    R_motor_CAN_map = 10,
    L_motor_CAN_map,
    R_motor_default_CAN_id,
    L_motor_default_CAN_id,
    car_max_lin_speed = 16,
    car_min_lin_speed = 18,
    car_max_ang_speed = 20,
    car_min_ang_speed = 22,
    car_tar_lin_speed = 24,
    car_tar_ang_speed = 26,
    // 航模参数
    turn_off_remote = 40,
    turn_on_remote,
    vel_base_value,
    dir_base_value,
    limit_max_val,
    limit_min_val,
    speed_level1,
    speed_level2,
    speed_level3,
    speed_low,
    speed_middle,
    speed_high,
    speed_dir_low,
    speed_dir_middle,
    speed_dir_high,
    light_base,
    light_max,
    light_min,
    // 电机参数
    motor1_state = 60,
    motor1_radius,
    motor1_reduction_ratio,
    motor1_CAN_id,
    motor1_CAN_baud,
    motor1_CAN_heartbeat,
    motor1_model,
    motor1_tar_torque,
    motor1_tar_speed = 69,
    motor1_tar_position = 71,

    motor2_state = 77,
    motor2_radius,
    motor2_reduction_ratio,
    motor2_CAN_id,
    motor2_CAN_baud,
    motor2_CAN_heartbeat,
    motor2_model,
    motor2_tar_torque,
    motor2_tar_speed = 86,
    motor2_tar_position = 88,

    motor3_state = 94,
    motor3_radius,
    motor3_reduction_ratio,
    motor3_CAN_id,
    motor3_CAN_baud,
    motor3_CAN_heartbeat,
    motor3_model,
    motor3_tar_torque,
    motor3_tar_speed = 103,
    motor3_tar_position = 105,

    motor4_state = 111,
    motor4_radius,
    motor4_reduction_ratio,
    motor4_CAN_id,
    motor4_CAN_baud,
    motor4_CAN_heartbeat,
    motor4_model,
    motor4_tar_torque,
    motor4_tar_speed = 120,
    motor4_tar_position = 122,

// RO参数
    // 小车参数
    car_type = 150,
    car_version,
    car_system_state,
    power_voltage,
    car_error_messages,
    car_light_messages,
    car_current_ctrl_mode,
    car_feedback_lin_speed = 158,
    car_feedback_ang_speed = 160,
    // 电机参数
    motor1_state_word = 171,
    motor1_on_line_state,
    motor1_error_messages,
    motor1_ctrl_mode,
    motor1_feedback_torque,
    motor1_feedback_speed = 177,
    motor1_feedback_position = 179,

    motor2_state_word = 181,
    motor2_on_line_state,
    motor2_error_messages,
    motor2_ctrl_mode,
    motor2_feedback_torque,
    motor2_feedback_speed = 187,
    motor2_feedback_position = 189,

    motor3_state_word = 191,
    motor3_on_line_state,
    motor3_error_messages,
    motor3_ctrl_mode,
    motor3_feedback_torque,
    motor3_feedback_speed = 197,
    motor3_feedback_position = 199,

    motor4_state_word = 201,
    motor4_on_line_state,
    motor4_error_messages,
    motor4_ctrl_mode,
    motor4_feedback_torque,
    motor4_feedback_speed = 207,
    motor4_feedback_position = 209,
    // 航模参数
    remote_ch1_value = 218,
    remote_ch2_value,
    remote_ch3_value,
    remote_ch4_value,
    remote_ch5_value,
    remote_ch6_value,
    remote_ch7_value,
    remote_ch8_value,
    remote_ch9_value,
    remote_ch10_value,
    remote_ch11_value,
    remote_ch12_value,
    remote_ch13_value,
    remote_ch14_value,
    remote_ch15_value,
    remote_ch16_value,
    remote_connect_state,

    motor_num = 248,

    empty_buff_num = 348,
    receive_buff_num = 349
};

#endif
