#ifndef __485_ADDRESS__h
#define __485_ADDRESS__h

enum address_485 {

    // RO参数
    // 小车参数
    car_type = 0,
    car_version,
    car_system_state,
    power_voltage,
    car_error_messages,
    car_light_messages,
    car_current_ctrl_mode,
    exio_input_status,
    car_feedback_lin_speed = 8,
    car_feedback_ang_speed = 10,
    BatteryStatus = 16,
    BatteryQuantity,
    BatteryVoltage,
    BatteryCurrent,
    BatteryTemperature,

    // 电机参数
    motor1_state_word = 21,
    motor1_on_line_state,
    motor1_error_messages,
    motor1_ctrl_mode,
    motor1_feedback_torque,
    motor1_feedback_speed = 27,
    motor1_feedback_position = 29,

    motor2_state_word = 31,
    motor2_on_line_state,
    motor2_error_messages,
    motor2_ctrl_mode,
    motor2_feedback_torque,
    motor2_feedback_speed = 37,
    motor2_feedback_position = 39,

    motor3_state_word = 41,
    motor3_on_line_state,
    motor3_error_messages,
    motor3_ctrl_mode,
    motor3_feedback_torque,
    motor3_feedback_speed = 47,
    motor3_feedback_position = 49,

    motor4_state_word = 51,
    motor4_on_line_state,
    motor4_error_messages,
    motor4_ctrl_mode,
    motor4_feedback_torque,
    motor4_feedback_speed = 57,
    motor4_feedback_position = 59,
    //RC小车参数     
    rc_car_speed = 62,
    rc_car_mileage_high,
    rc_car_mileage_low,
    // 航模参数
    remote_ch1_value = 68,
    remote_ch2_value,
    remote_ch3_value,
    remote_ch4_value,
    remote_ch5_value,
    remote_ch6_value,
    remote_ch7_value,
    remote_ch8_value,
    remote_ch9_value,
    remote_ch10_value,
    remote_ch11_value,
    remote_ch12_value,
    remote_ch13_value,
    remote_ch14_value,
    remote_ch15_value,
    remote_ch16_value,
    remote_connect_state,
    adc1_jt_value,
    adc2_value,
    adc_yl_1,
    adc_yl_2,
    adc_yl_3,
    adc_yl_4,
    adc_yl_5,
    Ultrasonic1_H,
    Ultrasonic1_L,
    Ultrasonic2_H,
    Ultrasonic2_L,
    rc_encoder_high,
    rc_encoder_low,
    motor_num,

// RW参数
    // 小车参数
    car_mode = 100,
    car_default_mode,
    car_model,//< 小车模型
    error_get_and_clear,
    wheel_distance,
    axles_distance,
    software_reset,
    can_reinitialize,
    para_save,
    battery_manufacturer,//< 电池厂家
    power_control,
    reserve_c,
    reserve_d,
    reserve_e,
    light_control,
    reserve_f,
    car_max_lin_speed = 116,
    car_min_lin_speed = 118,
    car_max_ang_speed = 120,
    car_min_ang_speed = 122,
    car_tar_lin_speed = 124,
    car_tar_ang_speed = 126,


    robot_acceleration = 133,
    robot_forward_direction=134,
    robot_turning_direction,
    moddbus_485_id,
    moddbus_485_baud,
    CAN_baud,
    // 航模参数
    turn_off_remote = 140,
    turn_on_remote,
    vel_base_value,
    dir_base_value,
    limit_max_val,
    limit_min_val,
    speed_level1,
    speed_level2,
    speed_level3,
    speed_low,
    speed_middle,
    speed_high,
    speed_dir_low,
    speed_dir_middle,
    speed_dir_high,
    light_base,
    light_max,
    light_min,
    // 电机参数
    motor1_direction = 160,
    motor1_radius,
    motor1_reduction_ratio,
    motor1_CAN_id,
    motor1_res,
    motor1_CAN_heartbeat,
    motor1_model,
    motor1_tar_torque,
    motor1_tar_speed = 169,
    motor1_tar_position = 171,

    motor2_direction = 177,
    motor2_radius,
    motor2_reduction_ratio,
    motor2_CAN_id,
    motor2_res,
    motor2_CAN_heartbeat,
    motor2_model,
    motor2_tar_torque,
    motor2_tar_speed = 186,
    motor2_tar_position = 188,

    motor3_direction = 194,
    motor3_radius,
    motor3_reduction_ratio,
    motor3_CAN_id,
    motor3_res,
    motor3_CAN_heartbeat,
    motor3_model,
    motor3_tar_torque,
    motor3_tar_speed = 203,
    motor3_tar_position = 205,

    motor4_direction = 211,
    motor4_radius,
    motor4_reduction_ratio,
    motor4_CAN_id,
    motor4_res,
    motor4_CAN_heartbeat,
    motor4_model,
    motor4_tar_torque,
    motor4_tar_speed = 220,
    motor4_tar_position = 222,


    // 航模参数
    virtually_remote_ch1_value = 268,
    virtually_remote_ch2_value,
    virtually_remote_ch3_value,
    virtually_remote_ch4_value,
    virtually_remote_ch5_value,
    virtually_remote_ch6_value,
    virtually_remote_ch7_value,
    virtually_remote_ch8_value,
    virtually_remote_ch9_value,
    virtually_remote_ch10_value,
    virtually_remote_ch11_value,
    virtually_remote_ch12_value,
    virtually_remote_ch13_value,
    virtually_remote_ch14_value,
    virtually_remote_ch15_value,
    virtually_remote_ch16_value,

    rc_encoder_reset = 300,//< 该参数写5，脉冲计数和编码器清零
    rc_encoder_dir,//< 0:按编码器方向加减;1:脉冲计数只累加
    rc_ratio,//< 减速比，精度0.001
    rc_encoder_accuracy,//< 编码器精度，精度1
    rc_tire_diameter,//< 轮胎直径，单位mm
    rc_speed_shifting,//< RC速度偏移
    rc_angle_shifting,//< RC转向偏移
    rc_magnification,//< RC速度倍率

    empty_buff_num = 348,
    receive_buff_num = 349
};

#endif
