#ifndef __485_ADDRESS__h
#define __485_ADDRESS__h

enum address_485 {
    // RO参数
    // 小车参数
    car_type = 0,
    car_version,
    car_system_state,
    power_voltage,
    car_error_messages,
    car_light_messages,
    car_current_ctrl_mode,
    exio_input_status,
    car_setting_lin_speed,
    car_setting_ang_speed,
    car_feedback_lin_speed,
    car_feedback_ang_speed,
    BatteryStatus,
    BatteryQuantity,
    BatteryVoltage,
    BatteryCurrent,
    BatteryTemperature,
    BatteryHealth,
    BatteryProtectStatus,
    undefined19,
    undefined20,
    // 电机参数
    motor1_state_word = 21,
    motor1_on_line_state,
    motor1_error_messages,
    motor1_ctrl_mode,
    motor1_feedback_torque,
    motor1_feedback_rpm,
    motor1_feedback_speed_high,
    motor1_feedback_speed_low,
    motor1_feedback_position_high,
    motor1_feedback_position_low,

    motor2_state_word = 31,
    motor2_on_line_state,
    motor2_error_messages,
    motor2_ctrl_mode,
    motor2_feedback_torque,
    motor2_feedback_rpm,
    motor2_feedback_speed_high,
    motor2_feedback_speed_low,
    motor2_feedback_position_high,
    motor2_feedback_position_low,

    motor3_state_word = 41,
    motor3_on_line_state,
    motor3_error_messages,
    motor3_ctrl_mode,
    motor3_feedback_torque,
    motor3_feedback_rpm,
    motor3_feedback_speed_high,
    motor3_feedback_speed_low,
    motor3_feedback_position_high,
    motor3_feedback_position_low,

    motor4_state_word = 51,
    motor4_on_line_state,
    motor4_error_messages,
    motor4_ctrl_mode,
    motor4_feedback_torque,
    motor4_feedback_rpm,
    motor4_feedback_speed_high,
    motor4_feedback_speed_low,
    motor4_feedback_position_high,
    motor4_feedback_position_low,

    undefined60,
    undefined61,
    //RC小车参数
    rc_car_speed = 62,
    rc_car_mileage_high,
    rc_car_mileage_low,
    undefined65,
    undefined66,
    undefined67,
    // 航模参数
    remote_ch1_value = 68,
    remote_ch2_value,
    remote_ch3_value,
    remote_ch4_value,
    remote_ch5_value,
    remote_ch6_value,
    remote_ch7_value,
    remote_ch8_value,
    remote_ch9_value,
    remote_ch10_value,
    remote_ch11_value,
    remote_ch12_value,
    remote_ch13_value,
    remote_ch14_value,
    remote_ch15_value,
    remote_ch16_value,
    remote_connect_state,
    adc1_jt_value,
    adc2_value,
    adc_yl_1,
    adc_yl_2,
    adc_yl_3,
    adc_yl_4,
    adc_yl_5,
    Ultrasonic1_H,
    Ultrasonic1_L,
    Ultrasonic2_H,
    Ultrasonic2_L,
    rc_encoder_high,
    rc_encoder_low,
    motor_num,

    // RW参数
        // 小车参数
    car_mode = 100,
    car_default_mode,
    car_model,//< 小车模型
    error_get_and_clear,
    wheel_distance,
    axles_distance,
    software_reset,
    can_reinitialize,
    para_save,
    battery_manufacturer,//< 电池厂家
    power_control,
    undefined111,
    undefined112,
    undefined113,
    light_control,
    undefined115,
    car_max_lin_speed,
    car_min_lin_speed,
    car_max_ang_speed,
    car_min_ang_speed,
    car_tar_lin_speed,
    car_tar_ang_speed,
    undefined122,
    undefined123,
    undefined124,
    undefined125,
    undefined126,
    undefined127,
    undefined128,
    undefined129,
    undefined130,
    undefined131,
    undefined132,
    robot_acceleration = 133,
    robot_forward_direction = 134,
    robot_turning_direction,
    moddbus_485_id,
    moddbus_485_baud,
    CAN_baud,
    // 航模参数
    turn_off_remote = 140,
    turn_on_remote,
    vel_base_value,
    dir_base_value,
    limit_max_val,
    limit_min_val,
    speed_level1,
    speed_level2,
    speed_level3,
    speed_low,
    speed_middle,
    speed_high,
    speed_dir_low,
    speed_dir_middle,
    speed_dir_high,
    light_base,
    light_max,
    light_min,
    // 电机参数
    motor1_direction = 160,
    motor1_radius,
    motor1_reduction_ratio,
    motor1_CAN_id,
    motor1_res,
    motor1_CAN_heartbeat,
    motor1_model,
    encoder_accuracy1,
    undefined168,
    undefined169,
    undefined170,
    undefined171,
    undefined172,
    undefined173,
    undefined174,
    undefined175,
    undefined176,
    motor2_direction = 177,
    motor2_radius,
    motor2_reduction_ratio,
    motor2_CAN_id,
    motor2_res,
    motor2_CAN_heartbeat,
    motor2_model,
    encoder_accuracy2,
    undefined185,
    undefined186,
    undefined187,
    undefined188,
    undefined189,
    undefined190,
    undefined191,
    undefined192,
    undefined193,
    motor3_direction = 194,
    motor3_radius,
    motor3_reduction_ratio,
    motor3_CAN_id,
    motor3_res,
    motor3_CAN_heartbeat,
    motor3_model,
    encoder_accuracy3,
    undefined202,
    undefined203,
    undefined204,
    undefined205,
    undefined206,
    undefined207,
    undefined208,
    undefined209,
    undefined210,
    motor4_direction = 211,
    motor4_radius,
    motor4_reduction_ratio,
    motor4_CAN_id,
    motor4_res,
    motor4_CAN_heartbeat,
    motor4_model,
    encoder_accuracy4,
    undefined219,
    undefined220,
    undefined221,
    undefined222,
    undefined223,
    undefined224,
    undefined225,
    undefined226,
    undefined227,


    // 航模参数
    virtually_remote_ch1_value = 268,
    virtually_remote_ch2_value,
    virtually_remote_ch3_value,
    virtually_remote_ch4_value,
    virtually_remote_ch5_value,
    virtually_remote_ch6_value,
    virtually_remote_ch7_value,
    virtually_remote_ch8_value,
    virtually_remote_ch9_value,
    virtually_remote_ch10_value,
    virtually_remote_ch11_value,
    virtually_remote_ch12_value,
    virtually_remote_ch13_value,
    virtually_remote_ch14_value,
    virtually_remote_ch15_value,
    virtually_remote_ch16_value,

    rc_encoder_reset = 300,//< 该参数写5，脉冲计数和编码器清零
    rc_encoder_dir,//< 0:按编码器方向加减;1:脉冲计数只累加
    rc_ratio,//< 减速比，精度0.001
    rc_encoder_accuracy,//< 编码器精度，精度1
    rc_tire_diameter,//< 轮胎直径，单位mm
    rc_speed_shifting,//< RC速度偏移
    rc_angle_shifting,//< RC转向偏移
    rc_magnification,//< RC速度倍率

    Middle_battery_threshold = 310,
    Low_battery_threshold,
};

#endif
